# -*- coding: utf-8 -*-
"""project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17BhYgh3piJ6MY2Jp4KbuMPF3v9lAIcN3
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv("/content/House_Prices.csv")

df.head()

df.info()

sns.heatmap(df.corr(numeric_only=True))

print(df.columns)

df = df.drop('Brick', axis = 1)

print(df.isnull().sum())

print(df['Neighborhood'].unique())

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Neighborhood'] = le.fit_transform(df['Neighborhood'])

print(df['Neighborhood'].head())
print(df['Neighborhood'].dtypes)

X = df.drop(['Home','Price','Offers'],axis=1)
y = df['Price']
print(X.head())
print(X.dtypes)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=300,max_depth=10, random_state=42)
model.fit(X_train, y_train)

print("R2 Score:", model.score(X_test, y_test))

import pickle
pickle.dump(model, open('model.pkl', 'wb'))

import pickle
model = pickle.load(open('model.pkl', 'rb'))

simple_input = np.array([[2000,3,2,1]])
prediction = model.predict(simple_input)
print('prediction Price:',prediction)

 Commented out IPython magic to ensure Python compatibility.
 %%writefile app.py
 import pickle
 import streamlit as st
 import numpy as np
 model = pickle.load(open('model.pkl', 'rb'))
 st.error("Model file not found. Please check the file path.")
 st.title('House Price Prediction')
 sqft = st.number_input("SqFt Area", min_value=0.0)
 bed = st.number_input("Bedrooms", min_value=0.0)
 bath = st.number_input("Bathrooms", min_value=0.0)
 nb = st.number_input("Neighborhood", options = [0,1,],help="0 for Area A,1 for Area B")
 
 if st.button("predict Price"):
   data = np.array([[sqft,bed,bath,nb]])
   prediction = model.predict(data)
   st.success('Predicted Price: {}'.format(prediction))


!pip install streamlit

!streamlit run app.py & npx localtunnel --port 8501

streamlit run app.py & npx localtunnel --port 8501

